GET http://localhost:3000/users

###
GET http://localhost:3000/users/2

###
POST http://localhost:3000/users 
Content-Type: application/json

{
  "username": "gabrielcardoso",
  "password": "123",
  "name": "Gabriel Cardoso",
  "email": "gcardoso@scoder.com.br",
  "phonenumber": "(35) 99883-5972"
}

###
PATCH http://localhost:3000/users/4
Content-Type: application/json

{
  "username": "kkkkkkkk",
  "password": "1234",
  "name": "kkkkkkkkkk",
  "email": "mabdias@scoder.com.br",
  "phonenumber": "(35) 99856-0346"
}

###
DELETE http://localhost:3000/users/4

###
GET http://localhost:3000/sync-exchanges

###
GET http://localhost:3000/sync-exchanges/4

###
POST http://localhost:3000/sync-exchanges 
Content-Type: application/json

{
  "exchange": "Tether",
  "api_key": "chavetestetether",
  "user_id": 3
}

###
PATCH http://localhost:3000/sync-exchanges/5
Content-Type: application/json

{
  "exchange": "Tether",
  "api_key": "chavetestetether",
  "user_id": 1
}

###
DELETE http://localhost:3000/sync-exchanges/1

