version: "3.8"

services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - overchain-network
    environment: 
      MYSQL_ROOT_PASSWORD: OverChain2022!
      MYSQL_DATABASE: overchain_crypto

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - overchain-network

networks:
  overchain-network:
    driver: bridge